server:
  port: 8080

spring:
  application:
    name: dubbo-consumer

dubbo:
  consumer:
    check: false
  protocol:
    name: dubbo
    port: -1
    serialization: fastjson2
  application:
    qos-enable: false
  registry:
    address: nacos://10.21.23.9:8848?username=nacos&password=nacos